//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Formulario_Proyecto_Final.ServicioClienteCredito {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioClienteCredito.ServicioClienteCredidoSoap")]
    public interface ServicioClienteCredidoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento numerocliente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Grabar", ReplyAction="*")]
        Formulario_Proyecto_Final.ServicioClienteCredito.GrabarResponse Grabar(Formulario_Proyecto_Final.ServicioClienteCredito.GrabarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Grabar", ReplyAction="*")]
        System.Threading.Tasks.Task<Formulario_Proyecto_Final.ServicioClienteCredito.GrabarResponse> GrabarAsync(Formulario_Proyecto_Final.ServicioClienteCredito.GrabarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ConsultarTrabajoDesempeñadoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarTrabajoDesempeñado", ReplyAction="*")]
        Formulario_Proyecto_Final.ServicioClienteCredito.ConsultarTrabajoDesempeñadoResponse ConsultarTrabajoDesempeñado(Formulario_Proyecto_Final.ServicioClienteCredito.ConsultarTrabajoDesempeñadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarTrabajoDesempeñado", ReplyAction="*")]
        System.Threading.Tasks.Task<Formulario_Proyecto_Final.ServicioClienteCredito.ConsultarTrabajoDesempeñadoResponse> ConsultarTrabajoDesempeñadoAsync(Formulario_Proyecto_Final.ServicioClienteCredito.ConsultarTrabajoDesempeñadoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GrabarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Grabar", Namespace="http://tempuri.org/", Order=0)]
        public Formulario_Proyecto_Final.ServicioClienteCredito.GrabarRequestBody Body;
        
        public GrabarRequest() {
        }
        
        public GrabarRequest(Formulario_Proyecto_Final.ServicioClienteCredito.GrabarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GrabarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numerocliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombre2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string apellido1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string apellido2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string domicilio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string trabajo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string referencia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string eficiencia;
        
        public GrabarRequestBody() {
        }
        
        public GrabarRequestBody(string numerocliente, string nombre1, string nombre2, string apellido1, string apellido2, string fecha, string domicilio, string trabajo, string referencia, string eficiencia) {
            this.numerocliente = numerocliente;
            this.nombre1 = nombre1;
            this.nombre2 = nombre2;
            this.apellido1 = apellido1;
            this.apellido2 = apellido2;
            this.fecha = fecha;
            this.domicilio = domicilio;
            this.trabajo = trabajo;
            this.referencia = referencia;
            this.eficiencia = eficiencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GrabarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GrabarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Formulario_Proyecto_Final.ServicioClienteCredito.GrabarResponseBody Body;
        
        public GrabarResponse() {
        }
        
        public GrabarResponse(Formulario_Proyecto_Final.ServicioClienteCredito.GrabarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GrabarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GrabarResult;
        
        public GrabarResponseBody() {
        }
        
        public GrabarResponseBody(bool GrabarResult) {
            this.GrabarResult = GrabarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarTrabajoDesempeñadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarTrabajoDesempeñado", Namespace="http://tempuri.org/", Order=0)]
        public Formulario_Proyecto_Final.ServicioClienteCredito.ConsultarTrabajoDesempeñadoRequestBody Body;
        
        public ConsultarTrabajoDesempeñadoRequest() {
        }
        
        public ConsultarTrabajoDesempeñadoRequest(Formulario_Proyecto_Final.ServicioClienteCredito.ConsultarTrabajoDesempeñadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarTrabajoDesempeñadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int valor;
        
        public ConsultarTrabajoDesempeñadoRequestBody() {
        }
        
        public ConsultarTrabajoDesempeñadoRequestBody(int valor) {
            this.valor = valor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarTrabajoDesempeñadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarTrabajoDesempeñadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Formulario_Proyecto_Final.ServicioClienteCredito.ConsultarTrabajoDesempeñadoResponseBody Body;
        
        public ConsultarTrabajoDesempeñadoResponse() {
        }
        
        public ConsultarTrabajoDesempeñadoResponse(Formulario_Proyecto_Final.ServicioClienteCredito.ConsultarTrabajoDesempeñadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarTrabajoDesempeñadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultarTrabajoDesempeñadoResult;
        
        public ConsultarTrabajoDesempeñadoResponseBody() {
        }
        
        public ConsultarTrabajoDesempeñadoResponseBody(string ConsultarTrabajoDesempeñadoResult) {
            this.ConsultarTrabajoDesempeñadoResult = ConsultarTrabajoDesempeñadoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioClienteCredidoSoapChannel : Formulario_Proyecto_Final.ServicioClienteCredito.ServicioClienteCredidoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClienteCredidoSoapClient : System.ServiceModel.ClientBase<Formulario_Proyecto_Final.ServicioClienteCredito.ServicioClienteCredidoSoap>, Formulario_Proyecto_Final.ServicioClienteCredito.ServicioClienteCredidoSoap {
        
        public ServicioClienteCredidoSoapClient() {
        }
        
        public ServicioClienteCredidoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClienteCredidoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteCredidoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteCredidoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formulario_Proyecto_Final.ServicioClienteCredito.GrabarResponse Formulario_Proyecto_Final.ServicioClienteCredito.ServicioClienteCredidoSoap.Grabar(Formulario_Proyecto_Final.ServicioClienteCredito.GrabarRequest request) {
            return base.Channel.Grabar(request);
        }
        
        public bool Grabar(string numerocliente, string nombre1, string nombre2, string apellido1, string apellido2, string fecha, string domicilio, string trabajo, string referencia, string eficiencia) {
            Formulario_Proyecto_Final.ServicioClienteCredito.GrabarRequest inValue = new Formulario_Proyecto_Final.ServicioClienteCredito.GrabarRequest();
            inValue.Body = new Formulario_Proyecto_Final.ServicioClienteCredito.GrabarRequestBody();
            inValue.Body.numerocliente = numerocliente;
            inValue.Body.nombre1 = nombre1;
            inValue.Body.nombre2 = nombre2;
            inValue.Body.apellido1 = apellido1;
            inValue.Body.apellido2 = apellido2;
            inValue.Body.fecha = fecha;
            inValue.Body.domicilio = domicilio;
            inValue.Body.trabajo = trabajo;
            inValue.Body.referencia = referencia;
            inValue.Body.eficiencia = eficiencia;
            Formulario_Proyecto_Final.ServicioClienteCredito.GrabarResponse retVal = ((Formulario_Proyecto_Final.ServicioClienteCredito.ServicioClienteCredidoSoap)(this)).Grabar(inValue);
            return retVal.Body.GrabarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formulario_Proyecto_Final.ServicioClienteCredito.GrabarResponse> Formulario_Proyecto_Final.ServicioClienteCredito.ServicioClienteCredidoSoap.GrabarAsync(Formulario_Proyecto_Final.ServicioClienteCredito.GrabarRequest request) {
            return base.Channel.GrabarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formulario_Proyecto_Final.ServicioClienteCredito.GrabarResponse> GrabarAsync(string numerocliente, string nombre1, string nombre2, string apellido1, string apellido2, string fecha, string domicilio, string trabajo, string referencia, string eficiencia) {
            Formulario_Proyecto_Final.ServicioClienteCredito.GrabarRequest inValue = new Formulario_Proyecto_Final.ServicioClienteCredito.GrabarRequest();
            inValue.Body = new Formulario_Proyecto_Final.ServicioClienteCredito.GrabarRequestBody();
            inValue.Body.numerocliente = numerocliente;
            inValue.Body.nombre1 = nombre1;
            inValue.Body.nombre2 = nombre2;
            inValue.Body.apellido1 = apellido1;
            inValue.Body.apellido2 = apellido2;
            inValue.Body.fecha = fecha;
            inValue.Body.domicilio = domicilio;
            inValue.Body.trabajo = trabajo;
            inValue.Body.referencia = referencia;
            inValue.Body.eficiencia = eficiencia;
            return ((Formulario_Proyecto_Final.ServicioClienteCredito.ServicioClienteCredidoSoap)(this)).GrabarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formulario_Proyecto_Final.ServicioClienteCredito.ConsultarTrabajoDesempeñadoResponse Formulario_Proyecto_Final.ServicioClienteCredito.ServicioClienteCredidoSoap.ConsultarTrabajoDesempeñado(Formulario_Proyecto_Final.ServicioClienteCredito.ConsultarTrabajoDesempeñadoRequest request) {
            return base.Channel.ConsultarTrabajoDesempeñado(request);
        }
        
        public string ConsultarTrabajoDesempeñado(int valor) {
            Formulario_Proyecto_Final.ServicioClienteCredito.ConsultarTrabajoDesempeñadoRequest inValue = new Formulario_Proyecto_Final.ServicioClienteCredito.ConsultarTrabajoDesempeñadoRequest();
            inValue.Body = new Formulario_Proyecto_Final.ServicioClienteCredito.ConsultarTrabajoDesempeñadoRequestBody();
            inValue.Body.valor = valor;
            Formulario_Proyecto_Final.ServicioClienteCredito.ConsultarTrabajoDesempeñadoResponse retVal = ((Formulario_Proyecto_Final.ServicioClienteCredito.ServicioClienteCredidoSoap)(this)).ConsultarTrabajoDesempeñado(inValue);
            return retVal.Body.ConsultarTrabajoDesempeñadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formulario_Proyecto_Final.ServicioClienteCredito.ConsultarTrabajoDesempeñadoResponse> Formulario_Proyecto_Final.ServicioClienteCredito.ServicioClienteCredidoSoap.ConsultarTrabajoDesempeñadoAsync(Formulario_Proyecto_Final.ServicioClienteCredito.ConsultarTrabajoDesempeñadoRequest request) {
            return base.Channel.ConsultarTrabajoDesempeñadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formulario_Proyecto_Final.ServicioClienteCredito.ConsultarTrabajoDesempeñadoResponse> ConsultarTrabajoDesempeñadoAsync(int valor) {
            Formulario_Proyecto_Final.ServicioClienteCredito.ConsultarTrabajoDesempeñadoRequest inValue = new Formulario_Proyecto_Final.ServicioClienteCredito.ConsultarTrabajoDesempeñadoRequest();
            inValue.Body = new Formulario_Proyecto_Final.ServicioClienteCredito.ConsultarTrabajoDesempeñadoRequestBody();
            inValue.Body.valor = valor;
            return ((Formulario_Proyecto_Final.ServicioClienteCredito.ServicioClienteCredidoSoap)(this)).ConsultarTrabajoDesempeñadoAsync(inValue);
        }
    }
}
